// 글자표 검색이 보는 한국어 이름과 찾는 말이다. zn(~/src/bluemir/zn) 의 특수문자 표
// (internal/assets/symbols.go 의 CuratedSymbols)에서 Name 과 Keywords 를 이어 옮겼다. 한 rune 으로 된
// 글자만 옮겼다. 여러 rune 으로 된 글자는 글자표에 오르지 않는다(runeList).
//
// 여기 없는 글자는 유니코드 영문 이름과 묶음 이름으로만 찾는다(glyphMatches).

package sketch

var glyphNames = map[string]string{
	"←": "왼쪽 화살표 화살표 arrow left",
	"→": "오른쪽 화살표 화살표 arrow right",
	"↑": "위쪽 화살표 화살표 arrow up",
	"↓": "아래쪽 화살표 화살표 arrow down",
	"↔": "좌우 화살표 화살표 arrow left right",
	"↕": "위아래 화살표 화살표 arrow up down",
	"↖": "왼쪽 위 화살표 화살표 arrow upper left",
	"↗": "오른쪽 위 화살표 화살표 arrow upper right",
	"↘": "오른쪽 아래 화살표 화살표 arrow lower right",
	"↙": "왼쪽 아래 화살표 화살표 arrow lower left",
	"↚": "왼쪽 화살표 부정 화살표 arrow left not",
	"↛": "오른쪽 화살표 부정 화살표 arrow right not",
	"↝": "물결 오른쪽 화살표 화살표 물결 arrow squiggle right",
	"↞": "왼쪽 두겹 머리 화살표 화살표 arrow left two head",
	"↠": "오른쪽 두겹 머리 화살표 화살표 arrow right two head",
	"↢": "왼쪽 꼬리 화살표 화살표 arrow left tail",
	"↣": "오른쪽 꼬리 화살표 화살표 arrow right tail",
	"↦": "오른쪽 막대 화살표 화살표 arrow maps to",
	"↩": "왼쪽 갈고리 화살표 화살표 arrow hook left",
	"↪": "오른쪽 갈고리 화살표 화살표 arrow hook right",
	"↰": "위에서 왼쪽 화살표 화살표 arrow up left",
	"↱": "위에서 오른쪽 화살표 화살표 arrow up right",
	"↲": "아래에서 왼쪽 화살표 화살표 arrow down left",
	"↳": "아래에서 오른쪽 화살표 화살표 arrow down right",
	"↵": "줄바꿈 화살표 화살표 엔터 arrow return enter newline",
	"↶": "반시계 반원 화살표 화살표 되돌리기 arrow undo anticlockwise",
	"↷": "시계 반원 화살표 화살표 다시하기 arrow redo clockwise",
	"↺": "반시계 열린 원 화살표 화살표 회전 arrow rotate anticlockwise",
	"↻": "시계 열린 원 화살표 화살표 회전 arrow rotate clockwise",
	"↼": "왼쪽 위 갈래 화살표 화살표 arrow harpoon left up",
	"⇀": "오른쪽 위 갈래 화살표 화살표 arrow harpoon right up",
	"⇄": "오른쪽 왼쪽 화살표 화살표 교환 arrow swap right left",
	"⇅": "위아래 나란한 화살표 화살표 arrow up down pair",
	"⇆": "왼쪽 오른쪽 화살표 화살표 교환 arrow swap left right",
	"⇇": "왼쪽 겹 화살표 화살표 arrow left pair",
	"⇉": "오른쪽 겹 화살표 화살표 arrow right pair",
	"⇐": "왼쪽 두 줄 화살표 화살표 arrow double left",
	"⇑": "위쪽 두 줄 화살표 화살표 arrow double up",
	"⇒": "오른쪽 두 줄 화살표 화살표 함의 arrow double right implies",
	"⇓": "아래쪽 두 줄 화살표 화살표 arrow double down",
	"⇔": "좌우 두 줄 화살표 화살표 동치 arrow double left right iff",
	"⇕": "위아래 두 줄 화살표 화살표 arrow double up down",
	"⇠": "왼쪽 점선 화살표 화살표 점선 arrow dashed left",
	"⇡": "위쪽 점선 화살표 화살표 점선 arrow dashed up",
	"⇢": "오른쪽 점선 화살표 화살표 점선 arrow dashed right",
	"⇣": "아래쪽 점선 화살표 화살표 점선 arrow dashed down",
	"⇦": "왼쪽 흰 화살표 화살표 arrow white left",
	"⇧": "위쪽 흰 화살표 화살표 시프트 arrow white up shift",
	"⇨": "오른쪽 흰 화살표 화살표 arrow white right",
	"⇩": "아래쪽 흰 화살표 화살표 arrow white down",
	"⇥": "오른쪽 막대 화살표 탭 화살표 탭 arrow tab right",
	"⇤": "왼쪽 막대 화살표 탭 화살표 탭 arrow tab left",
	"⌁": "되돌림 arrow delete escape",
	"⌃": "위 꺾쇠 컨트롤 컨트롤 control caret up",
	"⌄": "아래 꺾쇠 caret down",
	"⌘": "커맨드 키 맥 명령 command mac cloverleaf",
	"⌥": "옵션 키 맥 알트 option alt mac",
	"⎋": "이스케이프 키 이스케이프 escape esc",
	"⏎": "리턴 키 엔터 리턴 return enter",
	"⏏": "꺼내기 이젝트 eject",
	"⌫": "지우기 왼쪽 백스페이스 backspace delete",
	"⌦": "지우기 오른쪽 딜리트 delete forward",
	"➔": "굵은 오른쪽 화살표 화살표 arrow heavy right",
	"➜": "굵은 둥근 오른쪽 화살표 화살표 arrow heavy round right",
	"➡": "오른쪽 화살표 그림 화살표 arrow right black",
	"⬅": "왼쪽 화살표 그림 화살표 arrow left black",
	"⬆": "위쪽 화살표 그림 화살표 arrow up black",
	"⬇": "아래쪽 화살표 그림 화살표 arrow down black",
	"⤴": "위로 굽은 화살표 화살표 arrow curve up",
	"⤵": "아래로 굽은 화살표 화살표 arrow curve down",
	"⟵": "긴 왼쪽 화살표 화살표 arrow long left",
	"⟶": "긴 오른쪽 화살표 화살표 arrow long right",
	"⟷": "긴 좌우 화살표 화살표 arrow long left right",
	"⟸": "긴 왼쪽 두 줄 화살표 화살표 arrow long double left",
	"⟹": "긴 오른쪽 두 줄 화살표 화살표 arrow long double right",
	"⟺": "긴 좌우 두 줄 화살표 화살표 arrow long double left right",
	"↯": "번개 화살표 화살표 번개 arrow lightning",
	"⇋": "평형 화살표 화살표 평형 arrow equilibrium",
	"⇌": "평형 화살표 반대 화살표 평형 arrow equilibrium",
	"▲": "검은 위쪽 삼각형 삼각형 세모 triangle up black",
	"△": "흰 위쪽 삼각형 삼각형 세모 triangle up white",
	"▼": "검은 아래쪽 삼각형 삼각형 세모 triangle down black",
	"▽": "흰 아래쪽 삼각형 삼각형 세모 triangle down white",
	"◀": "검은 왼쪽 삼각형 삼각형 세모 triangle left black",
	"◁": "흰 왼쪽 삼각형 삼각형 세모 triangle left white",
	"▶": "검은 오른쪽 삼각형 삼각형 세모 triangle right black",
	"▷": "흰 오른쪽 삼각형 삼각형 세모 triangle right white",
	"▴": "검은 작은 위쪽 삼각형 삼각형 세모 triangle up small black",
	"▵": "흰 작은 위쪽 삼각형 삼각형 세모 triangle up small white",
	"▾": "검은 작은 아래쪽 삼각형 삼각형 세모 triangle down small black",
	"▿": "흰 작은 아래쪽 삼각형 삼각형 세모 triangle down small white",
	"◂": "검은 작은 왼쪽 삼각형 삼각형 세모 triangle left small black",
	"◃": "흰 작은 왼쪽 삼각형 삼각형 세모 triangle left small white",
	"▸": "검은 작은 오른쪽 삼각형 삼각형 세모 triangle right small black",
	"▹": "흰 작은 오른쪽 삼각형 삼각형 세모 triangle right small white",
	"◤": "검은 왼쪽 위 삼각형 삼각형 세모 triangle upper left",
	"◥": "검은 오른쪽 위 삼각형 삼각형 세모 triangle upper right",
	"◣": "검은 왼쪽 아래 삼각형 삼각형 세모 triangle lower left",
	"◢": "검은 오른쪽 아래 삼각형 삼각형 세모 triangle lower right",
	"⊿": "직각 삼각형 삼각형 세모 triangle right angle",
	"■": "검은 사각형 네모 사각형 square black",
	"□": "흰 사각형 네모 사각형 square white",
	"▪": "검은 작은 사각형 네모 사각형 square small black",
	"▫": "흰 작은 사각형 네모 사각형 square small white",
	"▬": "검은 가로 막대 네모 막대 rectangle black",
	"▭": "흰 가로 막대 네모 막대 rectangle white",
	"▮": "검은 세로 막대 네모 막대 rectangle vertical black",
	"▯": "흰 세로 막대 네모 막대 rectangle vertical white",
	"◆": "검은 마름모 마름모 다이아 diamond black",
	"◇": "흰 마름모 마름모 다이아 diamond white",
	"◈": "마름모 속 마름모 마름모 다이아 diamond in diamond",
	"◊": "마름모꼴 마름모 다이아 lozenge",
	"●": "검은 원 동그라미 원 circle black",
	"○": "흰 원 동그라미 원 circle white",
	"◎": "겹동그라미 동그라미 원 circle bullseye",
	"◉": "가운데 찬 동그라미 동그라미 원 circle fisheye",
	"◌": "점선 동그라미 동그라미 원 circle dotted",
	"◯": "큰 원 동그라미 원 circle large",
	"⬤": "큰 검은 원 동그라미 원 circle large black",
	"◐": "왼쪽 반 검은 원 동그라미 반원 circle half left",
	"◑": "오른쪽 반 검은 원 동그라미 반원 circle half right",
	"◒": "아래 반 검은 원 동그라미 반원 circle half bottom",
	"◓": "위 반 검은 원 동그라미 반원 circle half top",
	"⬛": "큰 검은 정사각형 네모 사각형 square large black",
	"⬜": "큰 흰 정사각형 네모 사각형 square large white",
	"⯀": "검은 중간 사각형 네모 사각형 square medium black",
	"★": "검은 별 별 star black",
	"☆": "흰 별 별 star white",
	"✦": "네 꼭짓점 검은 별 별 star four point",
	"✧": "네 꼭짓점 흰 별 별 star four point white",
	"✩": "얇은 흰 별 별 star outline",
	"✪": "동그라미 속 별 별 star circled",
	"✫": "가운데 뚫린 별 별 star open centre",
	"✮": "가운데 찬 별 별 star centre",
	"✯": "회전한 별 별 star pinwheel",
	"❂": "동그라미 속 여덟살 별 별 star circled eight",
	"✱": "굵은 별표 별표 asterisk heavy",
	"✲": "열린 별표 별표 asterisk open",
	"❉": "여섯살 별표 별표 asterisk six",
	"❋": "여덟살 별표 별표 asterisk eight",
	"⬟": "검은 오각형 오각형 pentagon black",
	"⬠": "흰 오각형 오각형 pentagon white",
	"⬢": "검은 육각형 육각형 hexagon black",
	"⬣": "흰 육각형 육각형 hexagon white",
	"⯃": "검은 팔각형 팔각형 octagon black",
	"▰": "검은 기울인 사각형 네모 사각형 parallelogram black",
	"▱": "흰 기울인 사각형 네모 사각형 parallelogram white",
	"◫": "세로로 나뉜 사각형 네모 사각형 square divided",
	"◪": "반쯤 찬 사각형 네모 사각형 square half filled",
	"▩": "빗금친 사각형 네모 사각형 square crosshatch",
	"▨": "빗금 사각형 네모 사각형 square diagonal hatch",
	"▤": "가로줄 사각형 네모 사각형 square horizontal fill",
	"▥": "세로줄 사각형 네모 사각형 square vertical fill",
	"▦": "격자 사각형 네모 사각형 square grid fill",
	"░": "옅은 음영 음영 블록 shade light",
	"▒": "중간 음영 음영 블록 shade medium",
	"▓": "짙은 음영 음영 블록 shade dark",
	"█": "꽉 찬 블록 블록 block full",
	"▄": "아래 반 블록 블록 block lower half",
	"▀": "위 반 블록 블록 block upper half",
	"▌": "왼쪽 반 블록 블록 block left half",
	"▐": "오른쪽 반 블록 블록 block right half",
	"▁": "아래 여덟분의 일 블록 블록 그래프 block eighth",
	"▂": "아래 사분의 일 블록 블록 그래프 block quarter",
	"▃": "아래 팔분의 삼 블록 블록 그래프 block",
	"▅": "아래 팔분의 오 블록 블록 그래프 block",
	"▆": "아래 사분의 삼 블록 블록 그래프 block",
	"▇": "아래 팔분의 칠 블록 블록 그래프 block",
	"±": "플러스 마이너스 더하기 빼기 plus minus",
	"∓": "마이너스 플러스 빼기 더하기 minus plus",
	"×": "곱하기 곱셈 multiply times",
	"÷": "나누기 나눗셈 divide",
	"∕": "나눗셈 사선 나눗셈 division slash",
	"∗": "별표 연산 곱 asterisk operator",
	"∘": "합성 고리 ring composition",
	"∙": "가운뎃점 연산 점 bullet operator",
	"⋅": "점 곱 점 dot product",
	"≠": "같지 않음 부등호 not equal",
	"≈": "거의 같음 근사 approximately equal",
	"≅": "합동 근사 congruent",
	"≡": "항등 합동 identical equivalent",
	"≢": "항등 아님 not identical",
	"≒": "근사 등호 근사 approximately equal",
	"≤": "작거나 같음 부등호 less than or equal",
	"≥": "크거나 같음 부등호 greater than or equal",
	"≪": "훨씬 작음 부등호 much less than",
	"≫": "훨씬 큼 부등호 much greater than",
	"∞": "무한대 무한 infinity",
	"∝": "비례 proportional to",
	"∂": "편미분 미분 partial differential",
	"∇": "나블라 델 nabla del gradient",
	"∫": "적분 integral",
	"∬": "이중 적분 적분 double integral",
	"∮": "선적분 적분 contour integral",
	"∑": "시그마 합 합 sum sigma",
	"∏": "파이 곱 곱 product pi",
	"√": "제곱근 루트 square root",
	"∛": "세제곱근 루트 cube root",
	"∜": "네제곱근 루트 fourth root",
	"∀": "모든 전칭 for all",
	"∃": "존재 존재 there exists",
	"∄": "존재하지 않음 there does not exist",
	"∅": "공집합 집합 empty set",
	"∈": "원소 집합 element of",
	"∉": "원소 아님 집합 not element of",
	"∋": "포함 원소 집합 contains as member",
	"⊂": "부분집합 집합 subset",
	"⊃": "포함집합 집합 superset",
	"⊆": "부분집합 또는 같음 집합 subset or equal",
	"⊇": "포함집합 또는 같음 집합 superset or equal",
	"⊄": "부분집합 아님 집합 not subset",
	"∪": "합집합 집합 union",
	"∩": "교집합 집합 intersection",
	"∖": "차집합 집합 set minus",
	"∧": "논리곱 그리고 logical and wedge",
	"∨": "논리합 또는 logical or vee",
	"¬": "부정 논리 not negation",
	"⊕": "배타적 논리합 엑스오 xor circled plus",
	"⊗": "텐서 곱 circled times tensor",
	"⊥": "수직 직교 perpendicular",
	"∥": "평행 parallel to",
	"∠": "각 각도 angle",
	"∟": "직각 각도 right angle",
	"°": "도 각도 온도 degree",
	"′": "프라임 분 prime minute",
	"″": "더블 프라임 초 double prime second",
	"∴": "그러므로 therefore",
	"∵": "왜냐하면 because",
	"∼": "물결 관계 닮음 tilde operator similar",
	"≃": "점근 같음 닮음 asymptotically equal",
	"≜": "정의에 의해 같음 정의 delta equal to",
	"≝": "정의됨 정의 equal by definition",
	"≟": "같은지 물음 questioned equal",
	"⌈": "천장 왼쪽 올림 ceiling left",
	"⌉": "천장 오른쪽 올림 ceiling right",
	"⌊": "바닥 왼쪽 내림 floor left",
	"⌋": "바닥 오른쪽 내림 floor right",
	"⟨": "왼쪽 꺾쇠 괄호 angle bracket left",
	"⟩": "오른쪽 꺾쇠 괄호 angle bracket right",
	"ℝ": "실수 집합 집합 real numbers",
	"ℕ": "자연수 집합 집합 natural numbers",
	"ℤ": "정수 집합 집합 integers",
	"ℚ": "유리수 집합 집합 rational numbers",
	"ℂ": "복소수 집합 집합 complex numbers",
	"ℵ": "알레프 aleph",
	"ℓ": "필기체 엘 script small l",
	"℘": "바이어슈트라스 피 weierstrass p",
	"ℏ": "플랑크 상수 planck constant hbar",
	"∎": "증명 끝 증명 end of proof qed",
	"⊤": "참 논리 top true",
	"⊢": "귀결 논리 turnstile proves",
	"⊨": "만족 논리 models entails",
	"⋮": "세로 생략 생략 vertical ellipsis",
	"⋯": "가운데 생략 생략 midline ellipsis",
	"⋱": "대각 생략 생략 diagonal ellipsis",
	"≺": "선행 순서 precedes",
	"≻": "후행 순서 succeeds",
	"⊑": "포함 사각 순서 square image of or equal",
	"⌀": "지름 공집합 diameter",
	"∆": "증분 델타 델타 increment delta",
	"µ": "마이크로 micro",
	"Ω": "옴 옴 ohm omega",
	"Å": "옹스트롬 angstrom",
	"‰": "퍼밀 천분율 per mille",
	"‱": "퍼밀리아드 만분율 per ten thousand",
	"%": "퍼센트 백분율 percent",
	"…": "말줄임표 생략 ellipsis dots",
	"‥": "두 점 말줄임 생략 two dot leader",
	"–": "엔 대시 줄표 en dash",
	"—": "엠 대시 줄표 em dash",
	"―": "가로줄 줄표 horizontal bar",
	"‐": "붙임표 하이픈 hyphen",
	"‑": "안 끊기는 붙임표 하이픈 non breaking hyphen",
	"·": "가운뎃점 점 middle dot interpunct",
	"•": "글머리 점 불릿 점 bullet",
	"◦": "흰 글머리 점 불릿 점 bullet white",
	"‣": "삼각 글머리 점 불릿 점 triangular bullet",
	"⁃": "하이픈 글머리 점 불릿 점 hyphen bullet",
	"‧": "이음 가운뎃점 점 hyphenation point",
	"†": "칼표 각주 dagger",
	"‡": "겹칼표 각주 double dagger",
	"§": "절 기호 섹션 section sign",
	"¶": "단락 기호 필크로 pilcrow paragraph",
	"‖": "겹세로줄 double vertical line",
	"¦": "끊긴 세로줄 broken bar",
	"“": "왼쪽 큰따옴표 따옴표 quote left double",
	"”": "오른쪽 큰따옴표 따옴표 quote right double",
	"‘": "왼쪽 작은따옴표 따옴표 quote left single",
	"’": "오른쪽 작은따옴표 따옴표 어퍼스트로피 quote right single apostrophe",
	"„": "아래 큰따옴표 따옴표 quote low double",
	"‚": "아래 작은따옴표 따옴표 quote low single",
	"«": "왼쪽 겹화살괄호 따옴표 guillemet left",
	"»": "오른쪽 겹화살괄호 따옴표 guillemet right",
	"‹": "왼쪽 홑화살괄호 따옴표 guillemet single left",
	"›": "오른쪽 홑화살괄호 따옴표 guillemet single right",
	"¡": "거꾸로 느낌표 느낌표 inverted exclamation",
	"¿": "거꾸로 물음표 물음표 inverted question",
	"‽": "물음느낌표 interrobang",
	"⁇": "겹물음표 물음표 double question",
	"⁈": "물음느낌 question exclamation",
	"⁉": "느낌물음 exclamation question",
	"‼": "겹느낌표 느낌표 double exclamation",
	"※": "참고표 코메 reference mark",
	"⁂": "별 세 개 asterism",
	"⌗": "우물 정 샵 해시 hash number sign",
	"№": "번호 넘버 numero",
	"℗": "저작인접권 phonogram copyright",
	"©": "저작권 카피라이트 copyright",
	"®": "등록상표 registered trademark",
	"™": "상표 트레이드마크 trademark",
	"℠": "서비스표 service mark",
	"＿": "전각 밑줄 밑줄 fullwidth low line",
	"〜": "물결표 물결 wave dash",
	"～": "전각 물결표 물결 fullwidth tilde",
	"〰": "물결 점선 물결 wavy dash",
	"ᵎ": "작은 느낌표 느낌표 small exclamation",
	"〽": "노래 기호 part alternation",
	"「": "홑낫표 열기 괄호 낫표 corner bracket left",
	"」": "홑낫표 닫기 괄호 낫표 corner bracket right",
	"『": "겹낫표 열기 괄호 낫표 white corner bracket left",
	"』": "겹낫표 닫기 괄호 낫표 white corner bracket right",
	"〈": "홑화살괄호 열기 괄호 angle bracket left",
	"〉": "홑화살괄호 닫기 괄호 angle bracket right",
	"《": "겹화살괄호 열기 괄호 double angle bracket left",
	"》": "겹화살괄호 닫기 괄호 double angle bracket right",
	"【": "굵은 대괄호 열기 괄호 black lenticular left",
	"】": "굵은 대괄호 닫기 괄호 black lenticular right",
	"〔": "거북 등 괄호 열기 괄호 tortoise shell left",
	"〕": "거북 등 괄호 닫기 괄호 tortoise shell right",
	"〖": "흰 대괄호 열기 괄호 white lenticular left",
	"〗": "흰 대괄호 닫기 괄호 white lenticular right",
	"（": "전각 소괄호 열기 괄호 fullwidth paren left",
	"）": "전각 소괄호 닫기 괄호 fullwidth paren right",
	"［": "전각 대괄호 열기 괄호 fullwidth bracket left",
	"］": "전각 대괄호 닫기 괄호 fullwidth bracket right",
	"｛": "전각 중괄호 열기 괄호 fullwidth brace left",
	"｝": "전각 중괄호 닫기 괄호 fullwidth brace right",
	"⦗": "굵은 홈 괄호 열기 괄호 tortoise shell bracket left",
	"⦘": "굵은 홈 괄호 닫기 괄호 tortoise shell bracket right",
	"⟦": "겹대괄호 열기 괄호 double bracket left",
	"⟧": "겹대괄호 닫기 괄호 double bracket right",
	"⟪": "겹꺾쇠 열기 괄호 double angle left",
	"⟫": "겹꺾쇠 닫기 괄호 double angle right",
	"⌜": "왼쪽 위 모서리 괄호 corner top left",
	"⌝": "오른쪽 위 모서리 괄호 corner top right",
	"⌞": "왼쪽 아래 모서리 괄호 corner bottom left",
	"⌟": "오른쪽 아래 모서리 괄호 corner bottom right",
	"₩": "원 화폐 통화 won korea",
	"$": "달러 화폐 통화 dollar",
	"¢": "센트 화폐 통화 cent",
	"€": "유로 화폐 통화 euro",
	"£": "파운드 화폐 통화 pound sterling",
	"¥": "엔 화폐 통화 yen japan",
	"元": "위안 화폐 통화 yuan china",
	"₽": "루블 화폐 통화 ruble russia",
	"₹": "루피 화폐 통화 rupee india",
	"₫": "동 화폐 통화 dong vietnam",
	"₺": "리라 화폐 통화 lira turkey",
	"₴": "흐리우냐 화폐 통화 hryvnia ukraine",
	"₦": "나이라 화폐 통화 naira nigeria",
	"₱": "페소 화폐 통화 peso philippines",
	"฿": "바트 화폐 통화 baht thailand",
	"₪": "셰켈 화폐 통화 shekel israel",
	"₸": "텡게 화폐 통화 tenge kazakhstan",
	"₡": "콜론 화폐 통화 colon",
	"₲": "과라니 화폐 통화 guarani",
	"₵": "세디 화폐 통화 cedi",
	"₭": "킵 화폐 통화 kip laos",
	"₮": "투그릭 화폐 통화 tugrik mongolia",
	"₾": "라리 화폐 통화 lari georgia",
	"¤": "통화 기호 화폐 통화 currency sign",
	"₿": "비트코인 화폐 통화 bitcoin",
	"─": "가로줄 괘선 박스 box horizontal",
	"│": "세로줄 괘선 박스 box vertical",
	"┌": "왼쪽 위 모서리 괘선 박스 box corner top left",
	"┐": "오른쪽 위 모서리 괘선 박스 box corner top right",
	"└": "왼쪽 아래 모서리 괘선 박스 box corner bottom left",
	"┘": "오른쪽 아래 모서리 괘선 박스 box corner bottom right",
	"├": "왼쪽 갈림 괘선 박스 box tee left",
	"┤": "오른쪽 갈림 괘선 박스 box tee right",
	"┬": "위 갈림 괘선 박스 box tee down",
	"┴": "아래 갈림 괘선 박스 box tee up",
	"┼": "십자 교차 괘선 박스 box cross",
	"━": "굵은 가로줄 괘선 박스 box horizontal heavy",
	"┃": "굵은 세로줄 괘선 박스 box vertical heavy",
	"┏": "굵은 왼쪽 위 모서리 괘선 박스 box heavy corner",
	"┓": "굵은 오른쪽 위 모서리 괘선 박스 box heavy corner",
	"┗": "굵은 왼쪽 아래 모서리 괘선 박스 box heavy corner",
	"┛": "굵은 오른쪽 아래 모서리 괘선 박스 box heavy corner",
	"┣": "굵은 왼쪽 갈림 괘선 박스 box heavy tee",
	"┫": "굵은 오른쪽 갈림 괘선 박스 box heavy tee",
	"┳": "굵은 위 갈림 괘선 박스 box heavy tee",
	"┻": "굵은 아래 갈림 괘선 박스 box heavy tee",
	"╋": "굵은 십자 교차 괘선 박스 box heavy cross",
	"═": "두 줄 가로줄 괘선 박스 box double horizontal",
	"║": "두 줄 세로줄 괘선 박스 box double vertical",
	"╔": "두 줄 왼쪽 위 모서리 괘선 박스 box double corner",
	"╗": "두 줄 오른쪽 위 모서리 괘선 박스 box double corner",
	"╚": "두 줄 왼쪽 아래 모서리 괘선 박스 box double corner",
	"╝": "두 줄 오른쪽 아래 모서리 괘선 박스 box double corner",
	"╠": "두 줄 왼쪽 갈림 괘선 박스 box double tee",
	"╣": "두 줄 오른쪽 갈림 괘선 박스 box double tee",
	"╦": "두 줄 위 갈림 괘선 박스 box double tee",
	"╩": "두 줄 아래 갈림 괘선 박스 box double tee",
	"╬": "두 줄 십자 교차 괘선 박스 box double cross",
	"╭": "둥근 왼쪽 위 모서리 괘선 박스 box round corner",
	"╮": "둥근 오른쪽 위 모서리 괘선 박스 box round corner",
	"╯": "둥근 오른쪽 아래 모서리 괘선 박스 box round corner",
	"╰": "둥근 왼쪽 아래 모서리 괘선 박스 box round corner",
	"╱": "오른쪽 위 대각선 괘선 박스 box diagonal",
	"╲": "오른쪽 아래 대각선 괘선 박스 box diagonal",
	"╳": "대각선 교차 괘선 박스 box diagonal cross",
	"┄": "점선 가로줄 괘선 박스 box dashed horizontal",
	"┆": "점선 세로줄 괘선 박스 box dashed vertical",
	"╌": "짧은 점선 가로줄 괘선 박스 box dashed horizontal",
	"╎": "짧은 점선 세로줄 괘선 박스 box dashed vertical",
	"✓": "체크 체크 확인 check mark tick",
	"✔": "굵은 체크 체크 확인 check mark heavy",
	"☑": "체크 상자 체크 확인 ballot box checked",
	"☐": "빈 상자 체크 ballot box empty",
	"☒": "엑스 상자 체크 ballot box x",
	"✗": "엑스 엑스 취소 ballot x",
	"✘": "굵은 엑스 엑스 취소 ballot x heavy",
	"✕": "곱셈 엑스 엑스 multiplication x",
	"✖": "굵은 곱셈 엑스 엑스 multiplication x heavy",
	"✚": "굵은 십자 더하기 heavy greek cross",
	"✛": "열린 십자 더하기 open centre cross",
	"⚠": "경고 주의 warning",
	"⚡": "번개 전기 high voltage lightning",
	"☠": "해골 죽음 skull crossbones",
	"☢": "방사능 위험 radioactive",
	"☣": "생물학적 위험 위험 biohazard",
	"♻": "재활용 recycling",
	"⚙": "톱니바퀴 설정 gear",
	"⚛": "원자 atom",
	"⚖": "저울 균형 scales balance",
	"⚓": "닻 anchor",
	"⚔": "칼 두 자루 무기 crossed swords",
	"⚑": "깃발 flag",
	"⚐": "흰 깃발 flag white",
	"⚕": "의료 지팡이 의료 medical staff aesculapius",
	"☮": "평화 peace",
	"☯": "음양 태극 yin yang",
	"☰": "건 삼괘 괘 trigram heaven",
	"☷": "곤 삼괘 괘 trigram earth",
	"♠": "스페이드 카드 spade",
	"♥": "하트 카드 사랑 heart",
	"♦": "다이아몬드 카드 diamond",
	"♣": "클로버 카드 club",
	"♤": "흰 스페이드 카드 spade white",
	"♡": "흰 하트 카드 사랑 heart white",
	"♢": "흰 다이아몬드 카드 diamond white",
	"♧": "흰 클로버 카드 club white",
	"☀": "해 날씨 sun",
	"☁": "구름 날씨 cloud",
	"☂": "우산 날씨 umbrella",
	"☃": "눈사람 날씨 snowman",
	"❄": "눈송이 날씨 snowflake",
	"☾": "초승달 달 crescent moon",
	"☽": "상현달 달 first quarter moon",
	"♀": "여성 성별 female venus",
	"♂": "남성 성별 male mars",
	"⚥": "남녀 성별 male and female",
	"♪": "8분음표 음악 음표 note eighth",
	"♫": "이어진 8분음표 음악 음표 note beamed",
	"♬": "이어진 16분음표 음악 음표 note beamed sixteenth",
	"♩": "4분음표 음악 음표 note quarter",
	"♭": "플랫 음악 flat",
	"♯": "샾 음악 sharp",
	"♮": "제자리표 음악 natural",
	"☎": "전화 phone telephone",
	"✉": "편지 메일 envelope mail",
	"✂": "가위 scissors",
	"✈": "비행기 airplane",
	"✏": "연필 pencil",
	"✒": "펜촉 nib pen",
	"☞": "오른쪽 손가락 손 pointing right hand",
	"☜": "왼쪽 손가락 손 pointing left hand",
	"☝": "위쪽 손가락 손 pointing up hand",
	"☟": "아래쪽 손가락 손 pointing down hand",
	"✍": "쓰는 손 손 writing hand",
	"⌚": "손목시계 시계 watch",
	"⌛": "모래시계 시계 hourglass",
	"⏰": "알람 시계 시계 alarm clock",
	"⏳": "흐르는 모래시계 시계 hourglass flowing",
	"⏱": "스톱워치 시계 stopwatch",
	"⏲": "타이머 시계 timer clock",
	"⚀": "주사위 일 주사위 die one",
	"⚁": "주사위 이 주사위 die two",
	"⚂": "주사위 삼 주사위 die three",
	"⚃": "주사위 사 주사위 die four",
	"⚄": "주사위 오 주사위 die five",
	"⚅": "주사위 육 주사위 die six",
	"☕": "커피 음료 hot beverage coffee",
	"♨": "온천 hot springs",
	"⚘": "꽃 flower",
	"✿": "겹꽃 flower blossom",
	"❀": "흰 꽃 flower white",
	"❁": "동그란 꽃 flower eight petalled",
	"☘": "세잎클로버 행운 shamrock",
	"⚜": "백합 문장 fleur de lis",
	"〄": "일본 공업 규격 jis mark",
	"♿": "휠체어 장애인 wheelchair",
	"⚟": "위쪽 반원 notched left semicircle",
	"⏩": "빨리 감기 재생 fast forward",
	"⏪": "되감기 재생 rewind",
	"⏸": "일시정지 재생 pause",
	"⏹": "정지 재생 stop",
	"⏺": "녹화 재생 record",
	"⏯": "재생 일시정지 재생 play pause",
	"♲": "재활용 흰색 recycling white",
	"✳": "여덟살 별표 별표 asterisk eight spoked",
	"✴": "여덟꼭짓점 별 별 star eight pointed",
	"❇": "반짝임 sparkle",
	"✨": "반짝반짝 sparkles",
	"❖": "검은 마름모 꽃 마름모 diamond minus",
	"➤": "검은 오른쪽 화살촉 화살표 arrowhead right",
	"➢": "오른쪽 화살촉 화살표 arrowhead right three",
	"⟡": "흰 마름모 마름모 diamond",
	"⌂": "집 house home",
	"⏻": "전원 power symbol",
	"⏼": "전원 켜짐 power on off",
	"⭘": "전원 끄기 power off",
	"α": "알파 그리스 greek alpha",
	"β": "베타 그리스 greek beta",
	"γ": "감마 그리스 greek gamma",
	"δ": "델타 그리스 greek delta",
	"ε": "엡실론 그리스 greek epsilon",
	"ζ": "제타 그리스 greek zeta",
	"η": "에타 그리스 greek eta",
	"θ": "세타 그리스 greek theta",
	"ι": "이오타 그리스 greek iota",
	"κ": "카파 그리스 greek kappa",
	"λ": "람다 그리스 greek lambda",
	"μ": "뮤 그리스 greek mu",
	"ν": "뉴 그리스 greek nu",
	"ξ": "크시 그리스 greek xi",
	"π": "파이 그리스 greek pi",
	"ρ": "로 그리스 greek rho",
	"σ": "시그마 그리스 greek sigma",
	"τ": "타우 그리스 greek tau",
	"υ": "윕실론 그리스 greek upsilon",
	"φ": "피 그리스 greek phi",
	"χ": "카이 그리스 greek chi",
	"ψ": "프시 그리스 greek psi",
	"ω": "오메가 그리스 greek omega",
	"Γ": "대문자 감마 그리스 greek capital gamma",
	"Δ": "대문자 델타 그리스 greek capital delta",
	"Θ": "대문자 세타 그리스 greek capital theta",
	"Λ": "대문자 람다 그리스 greek capital lambda",
	"Ξ": "대문자 크시 그리스 greek capital xi",
	"Π": "대문자 파이 그리스 greek capital pi",
	"Σ": "대문자 시그마 그리스 greek capital sigma",
	"Φ": "대문자 피 그리스 greek capital phi",
	"Ψ": "대문자 프시 그리스 greek capital psi",
	"⁰": "0 위첨자 위첨자 첨자 superscript 0",
	"¹": "1 위첨자 위첨자 첨자 superscript 1",
	"²": "2 위첨자 위첨자 첨자 superscript 2",
	"³": "3 위첨자 위첨자 첨자 superscript 3",
	"⁴": "4 위첨자 위첨자 첨자 superscript 4",
	"⁵": "5 위첨자 위첨자 첨자 superscript 5",
	"⁶": "6 위첨자 위첨자 첨자 superscript 6",
	"⁷": "7 위첨자 위첨자 첨자 superscript 7",
	"⁸": "8 위첨자 위첨자 첨자 superscript 8",
	"⁹": "9 위첨자 위첨자 첨자 superscript 9",
	"⁺": "더하기 위첨자 위첨자 첨자 superscript plus",
	"⁻": "빼기 위첨자 위첨자 첨자 superscript minus",
	"ⁿ": "n 위첨자 위첨자 첨자 superscript n",
	"₀": "0 아래첨자 아래첨자 첨자 subscript 0",
	"₁": "1 아래첨자 아래첨자 첨자 subscript 1",
	"₂": "2 아래첨자 아래첨자 첨자 subscript 2",
	"₃": "3 아래첨자 아래첨자 첨자 subscript 3",
	"₄": "4 아래첨자 아래첨자 첨자 subscript 4",
	"₅": "5 아래첨자 아래첨자 첨자 subscript 5",
	"₆": "6 아래첨자 아래첨자 첨자 subscript 6",
	"₇": "7 아래첨자 아래첨자 첨자 subscript 7",
	"₈": "8 아래첨자 아래첨자 첨자 subscript 8",
	"₉": "9 아래첨자 아래첨자 첨자 subscript 9",
	"₊": "더하기 아래첨자 아래첨자 첨자 subscript plus",
	"₋": "빼기 아래첨자 아래첨자 첨자 subscript minus",
	"½": "이분의 일 분수 fraction half",
	"⅓": "삼분의 일 분수 fraction third",
	"⅔": "삼분의 이 분수 fraction two thirds",
	"¼": "사분의 일 분수 fraction quarter",
	"¾": "사분의 삼 분수 fraction three quarters",
	"⅕": "오분의 일 분수 fraction fifth",
	"⅛": "팔분의 일 분수 fraction eighth",
	"⅜": "팔분의 삼 분수 fraction three eighths",
	"⅚": "육분의 오 분수 fraction five sixths",
	"⅞": "팔분의 칠 분수 fraction seven eighths",
	"Ⅰ": "로마 숫자 1 로마 숫자 roman numeral one",
	"Ⅱ": "로마 숫자 2 로마 숫자 roman numeral two",
	"Ⅲ": "로마 숫자 3 로마 숫자 roman numeral three",
	"Ⅳ": "로마 숫자 4 로마 숫자 roman numeral four",
	"Ⅴ": "로마 숫자 5 로마 숫자 roman numeral five",
	"Ⅵ": "로마 숫자 6 로마 숫자 roman numeral six",
	"Ⅶ": "로마 숫자 7 로마 숫자 roman numeral seven",
	"Ⅷ": "로마 숫자 8 로마 숫자 roman numeral eight",
	"Ⅸ": "로마 숫자 9 로마 숫자 roman numeral nine",
	"Ⅹ": "로마 숫자 10 로마 숫자 roman numeral ten",
	"①": "동그라미 숫자 1 원문자 동그라미 숫자 circled number 1",
	"②": "동그라미 숫자 2 원문자 동그라미 숫자 circled number 2",
	"③": "동그라미 숫자 3 원문자 동그라미 숫자 circled number 3",
	"④": "동그라미 숫자 4 원문자 동그라미 숫자 circled number 4",
	"⑤": "동그라미 숫자 5 원문자 동그라미 숫자 circled number 5",
	"⑥": "동그라미 숫자 6 원문자 동그라미 숫자 circled number 6",
	"⑦": "동그라미 숫자 7 원문자 동그라미 숫자 circled number 7",
	"⑧": "동그라미 숫자 8 원문자 동그라미 숫자 circled number 8",
	"⑨": "동그라미 숫자 9 원문자 동그라미 숫자 circled number 9",
	"⑩": "동그라미 숫자 10 원문자 동그라미 숫자 circled number 10",
	"⑪": "동그라미 숫자 11 원문자 동그라미 숫자 circled number 11",
	"⑫": "동그라미 숫자 12 원문자 동그라미 숫자 circled number 12",
	"⑬": "동그라미 숫자 13 원문자 동그라미 숫자 circled number 13",
	"⑭": "동그라미 숫자 14 원문자 동그라미 숫자 circled number 14",
	"⑮": "동그라미 숫자 15 원문자 동그라미 숫자 circled number 15",
	"⑯": "동그라미 숫자 16 원문자 동그라미 숫자 circled number 16",
	"⑰": "동그라미 숫자 17 원문자 동그라미 숫자 circled number 17",
	"⑱": "동그라미 숫자 18 원문자 동그라미 숫자 circled number 18",
	"⑲": "동그라미 숫자 19 원문자 동그라미 숫자 circled number 19",
	"⑳": "동그라미 숫자 20 원문자 동그라미 숫자 circled number 20",
	"❶": "검은 동그라미 숫자 1 원문자 동그라미 숫자 circled number black 1",
	"❷": "검은 동그라미 숫자 2 원문자 동그라미 숫자 circled number black 2",
	"❸": "검은 동그라미 숫자 3 원문자 동그라미 숫자 circled number black 3",
	"❹": "검은 동그라미 숫자 4 원문자 동그라미 숫자 circled number black 4",
	"❺": "검은 동그라미 숫자 5 원문자 동그라미 숫자 circled number black 5",
	"❻": "검은 동그라미 숫자 6 원문자 동그라미 숫자 circled number black 6",
	"❼": "검은 동그라미 숫자 7 원문자 동그라미 숫자 circled number black 7",
	"❽": "검은 동그라미 숫자 8 원문자 동그라미 숫자 circled number black 8",
	"❾": "검은 동그라미 숫자 9 원문자 동그라미 숫자 circled number black 9",
	"❿": "검은 동그라미 숫자 10 원문자 동그라미 숫자 circled number black 10",
	"⑴": "괄호 숫자 1 괄호 숫자 parenthesized number 1",
	"⑵": "괄호 숫자 2 괄호 숫자 parenthesized number 2",
	"⑶": "괄호 숫자 3 괄호 숫자 parenthesized number 3",
	"⑷": "괄호 숫자 4 괄호 숫자 parenthesized number 4",
	"⑸": "괄호 숫자 5 괄호 숫자 parenthesized number 5",
	"⑹": "괄호 숫자 6 괄호 숫자 parenthesized number 6",
	"⑺": "괄호 숫자 7 괄호 숫자 parenthesized number 7",
	"⑻": "괄호 숫자 8 괄호 숫자 parenthesized number 8",
	"⑼": "괄호 숫자 9 괄호 숫자 parenthesized number 9",
	"⑽": "괄호 숫자 10 괄호 숫자 parenthesized number 10",
	"㎜": "밀리미터 단위 unit millimeter mm",
	"㎝": "센티미터 단위 unit centimeter cm",
	"㎞": "킬로미터 단위 unit kilometer km",
	"㎡": "제곱미터 단위 unit square meter",
	"㎥": "세제곱미터 단위 unit cubic meter",
	"㎏": "킬로그램 단위 unit kilogram kg",
	"㎎": "밀리그램 단위 unit milligram mg",
	"㎖": "밀리리터 단위 unit milliliter ml",
	"㏄": "시시 단위 unit cc",
	"㎈": "킬로칼로리 단위 unit kilocalorie",
	"℃": "섭씨 온도 단위 unit celsius degree",
	"℉": "화씨 온도 단위 unit fahrenheit degree",
	"㎐": "헤르츠 단위 unit hertz hz",
	"㎅": "킬로바이트 단위 unit kilobyte kb",
	"㎆": "메가바이트 단위 unit megabyte mb",
	"㎇": "기가바이트 단위 unit gigabyte gb",
	"㎾": "킬로와트 단위 unit kilowatt kw",
	"㏈": "데시벨 단위 unit decibel db",
	"㎳": "밀리초 단위 unit millisecond ms",
	"㎲": "마이크로초 단위 unit microsecond",
	"㉠": "동그라미 ㄱ 원문자 동그라미 한글 자음 circled hangul ㄱ",
	"㉡": "동그라미 ㄴ 원문자 동그라미 한글 자음 circled hangul ㄴ",
	"㉢": "동그라미 ㄷ 원문자 동그라미 한글 자음 circled hangul ㄷ",
	"㉣": "동그라미 ㄹ 원문자 동그라미 한글 자음 circled hangul ㄹ",
	"㉤": "동그라미 ㅁ 원문자 동그라미 한글 자음 circled hangul ㅁ",
	"㉥": "동그라미 ㅂ 원문자 동그라미 한글 자음 circled hangul ㅂ",
	"㉦": "동그라미 ㅅ 원문자 동그라미 한글 자음 circled hangul ㅅ",
	"㉧": "동그라미 ㅇ 원문자 동그라미 한글 자음 circled hangul ㅇ",
	"㉨": "동그라미 ㅈ 원문자 동그라미 한글 자음 circled hangul ㅈ",
	"㉩": "동그라미 ㅊ 원문자 동그라미 한글 자음 circled hangul ㅊ",
	"㉪": "동그라미 ㅋ 원문자 동그라미 한글 자음 circled hangul ㅋ",
	"㉫": "동그라미 ㅌ 원문자 동그라미 한글 자음 circled hangul ㅌ",
	"㉬": "동그라미 ㅍ 원문자 동그라미 한글 자음 circled hangul ㅍ",
	"㉭": "동그라미 ㅎ 원문자 동그라미 한글 자음 circled hangul ㅎ",
	"㉮": "동그라미 가 원문자 동그라미 한글 circled hangul 가",
	"㉯": "동그라미 나 원문자 동그라미 한글 circled hangul 나",
	"㉰": "동그라미 다 원문자 동그라미 한글 circled hangul 다",
	"㉱": "동그라미 라 원문자 동그라미 한글 circled hangul 라",
	"㉲": "동그라미 마 원문자 동그라미 한글 circled hangul 마",
	"㉳": "동그라미 바 원문자 동그라미 한글 circled hangul 바",
	"㉴": "동그라미 사 원문자 동그라미 한글 circled hangul 사",
	"㉵": "동그라미 아 원문자 동그라미 한글 circled hangul 아",
	"㉶": "동그라미 자 원문자 동그라미 한글 circled hangul 자",
	"㉷": "동그라미 차 원문자 동그라미 한글 circled hangul 차",
	"㉸": "동그라미 카 원문자 동그라미 한글 circled hangul 카",
	"㉹": "동그라미 타 원문자 동그라미 한글 circled hangul 타",
	"㉺": "동그라미 파 원문자 동그라미 한글 circled hangul 파",
	"㉻": "동그라미 하 원문자 동그라미 한글 circled hangul 하",
	"㈀": "괄호 ㄱ 괄호 한글 자음 parenthesized hangul ㄱ",
	"㈁": "괄호 ㄴ 괄호 한글 자음 parenthesized hangul ㄴ",
	"㈂": "괄호 ㄷ 괄호 한글 자음 parenthesized hangul ㄷ",
	"㈃": "괄호 ㄹ 괄호 한글 자음 parenthesized hangul ㄹ",
	"㈄": "괄호 ㅁ 괄호 한글 자음 parenthesized hangul ㅁ",
	"㈅": "괄호 ㅂ 괄호 한글 자음 parenthesized hangul ㅂ",
	"㈆": "괄호 ㅅ 괄호 한글 자음 parenthesized hangul ㅅ",
	"㈇": "괄호 ㅇ 괄호 한글 자음 parenthesized hangul ㅇ",
	"㈈": "괄호 ㅈ 괄호 한글 자음 parenthesized hangul ㅈ",
	"㈉": "괄호 ㅊ 괄호 한글 자음 parenthesized hangul ㅊ",
	"㈊": "괄호 ㅋ 괄호 한글 자음 parenthesized hangul ㅋ",
	"㈋": "괄호 ㅌ 괄호 한글 자음 parenthesized hangul ㅌ",
	"㈌": "괄호 ㅍ 괄호 한글 자음 parenthesized hangul ㅍ",
	"㈍": "괄호 ㅎ 괄호 한글 자음 parenthesized hangul ㅎ",
	"㈎": "괄호 가 괄호 한글 parenthesized hangul 가",
	"㈏": "괄호 나 괄호 한글 parenthesized hangul 나",
	"㈐": "괄호 다 괄호 한글 parenthesized hangul 다",
	"㈑": "괄호 라 괄호 한글 parenthesized hangul 라",
	"㈒": "괄호 마 괄호 한글 parenthesized hangul 마",
	"㈓": "괄호 바 괄호 한글 parenthesized hangul 바",
	"㈔": "괄호 사 괄호 한글 parenthesized hangul 사",
	"㈕": "괄호 아 괄호 한글 parenthesized hangul 아",
	"㈖": "괄호 자 괄호 한글 parenthesized hangul 자",
	"㈗": "괄호 차 괄호 한글 parenthesized hangul 차",
	"㈘": "괄호 카 괄호 한글 parenthesized hangul 카",
	"㈙": "괄호 타 괄호 한글 parenthesized hangul 타",
	"㈚": "괄호 파 괄호 한글 parenthesized hangul 파",
	"㈛": "괄호 하 괄호 한글 parenthesized hangul 하",
	"😀": "활짝 웃는 얼굴 이모지 표정 웃음 grinning face",
	"😃": "눈웃음 짓는 얼굴 이모지 표정 웃음 grinning big eyes",
	"😄": "웃으며 눈웃음 짓는 얼굴 이모지 표정 웃음 grinning smiling eyes",
	"😁": "활짝 웃으며 눈웃음 이모지 표정 웃음 beaming face",
	"😆": "눈 감고 크게 웃는 얼굴 이모지 표정 웃음 grinning squinting",
	"😅": "식은땀 흘리며 웃는 얼굴 이모지 표정 웃음 땀 grinning sweat",
	"🤣": "바닥을 구르며 웃는 얼굴 이모지 표정 웃음 rolling on the floor laughing",
	"😂": "눈물 나게 웃는 얼굴 이모지 표정 웃음 눈물 tears of joy",
	"🙂": "살짝 웃는 얼굴 이모지 표정 웃음 slightly smiling",
	"🙃": "거꾸로 된 얼굴 이모지 표정 upside down face",
	"😉": "윙크하는 얼굴 이모지 표정 winking face",
	"😊": "활짝 웃는 눈웃음 얼굴 이모지 표정 웃음 smiling eyes",
	"😇": "천사 얼굴 이모지 표정 halo angel",
	"🥰": "하트에 둘러싸인 얼굴 이모지 표정 사랑 smiling hearts",
	"😍": "하트 눈 얼굴 이모지 표정 사랑 heart eyes",
	"🤩": "별 눈 얼굴 이모지 표정 star struck",
	"😘": "뽀뽀하는 얼굴 이모지 표정 사랑 blowing a kiss",
	"😗": "입 오므린 얼굴 이모지 표정 kissing face",
	"😚": "눈 감고 뽀뽀하는 얼굴 이모지 표정 kissing closed eyes",
	"😙": "웃으며 뽀뽀하는 얼굴 이모지 표정 kissing smiling eyes",
	"😋": "맛있는 얼굴 이모지 표정 savoring food yum",
	"😛": "혀 내민 얼굴 이모지 표정 tongue out",
	"😜": "윙크하며 혀 내민 얼굴 이모지 표정 winking tongue",
	"🤪": "엉뚱한 얼굴 이모지 표정 zany face",
	"😝": "눈 감고 혀 내민 얼굴 이모지 표정 squinting tongue",
	"🤑": "돈 좋아하는 얼굴 이모지 표정 돈 money mouth",
	"🤗": "안아주는 얼굴 이모지 표정 hugging face",
	"🤭": "입 가린 얼굴 이모지 표정 hand over mouth",
	"🤫": "조용히 하라는 얼굴 이모지 표정 shushing face",
	"🤔": "생각하는 얼굴 이모지 표정 thinking face",
	"🤐": "입 지퍼 얼굴 이모지 표정 zipper mouth",
	"🤨": "눈썹 치켜올린 얼굴 이모지 표정 raised eyebrow",
	"😐": "무표정한 얼굴 이모지 표정 neutral face",
	"😑": "심드렁한 얼굴 이모지 표정 expressionless",
	"😶": "입 없는 얼굴 이모지 표정 no mouth",
	"😏": "능글맞은 얼굴 이모지 표정 smirking face",
	"😒": "떨떠름한 얼굴 이모지 표정 unamused face",
	"🙄": "눈 굴리는 얼굴 이모지 표정 rolling eyes",
	"😬": "이 드러낸 얼굴 이모지 표정 grimacing face",
	"🤥": "거짓말하는 얼굴 이모지 표정 lying face",
	"😌": "안도하는 얼굴 이모지 표정 relieved face",
	"😔": "시무룩한 얼굴 이모지 표정 pensive face",
	"😪": "졸린 얼굴 이모지 표정 sleepy face",
	"🤤": "침 흘리는 얼굴 이모지 표정 drooling face",
	"😴": "자는 얼굴 이모지 표정 sleeping face",
	"😷": "마스크 쓴 얼굴 이모지 표정 medical mask",
	"🤒": "체온계 문 얼굴 이모지 표정 face with thermometer",
	"🤕": "머리 다친 얼굴 이모지 표정 head bandage",
	"🤢": "메스꺼운 얼굴 이모지 표정 nauseated face",
	"🤮": "토하는 얼굴 이모지 표정 vomiting face",
	"🤧": "재채기하는 얼굴 이모지 표정 sneezing face",
	"🥵": "더워하는 얼굴 이모지 표정 hot face",
	"🥶": "추워하는 얼굴 이모지 표정 cold face",
	"😵": "어지러운 얼굴 이모지 표정 dizzy face",
	"🤯": "머리 터지는 얼굴 이모지 표정 exploding head",
	"🤠": "카우보이 얼굴 이모지 표정 cowboy hat",
	"🥳": "파티하는 얼굴 이모지 표정 partying face",
	"😎": "선글라스 낀 얼굴 이모지 표정 sunglasses cool",
	"🤓": "안경 쓴 얼굴 이모지 표정 nerd face",
	"🧐": "외알 안경 얼굴 이모지 표정 monocle",
	"😕": "헷갈리는 얼굴 이모지 표정 confused face",
	"😟": "걱정하는 얼굴 이모지 표정 worried face",
	"🙁": "살짝 찡그린 얼굴 이모지 표정 slightly frowning",
	"😮": "입 벌린 얼굴 이모지 표정 open mouth",
	"😯": "놀란 얼굴 이모지 표정 hushed face",
	"😲": "깜짝 놀란 얼굴 이모지 표정 astonished face",
	"😳": "얼굴 붉힌 얼굴 이모지 표정 flushed face",
	"🥺": "애원하는 얼굴 이모지 표정 pleading face",
	"😦": "찡그리며 입 벌린 얼굴 이모지 표정 frowning open mouth",
	"😨": "겁먹은 얼굴 이모지 표정 fearful face",
	"😰": "식은땀 흘리는 얼굴 이모지 표정 땀 anxious sweat",
	"😥": "슬픈 안도의 얼굴 이모지 표정 sad but relieved",
	"😢": "우는 얼굴 이모지 표정 눈물 crying face",
	"😭": "엉엉 우는 얼굴 이모지 표정 눈물 loudly crying",
	"😱": "비명 지르는 얼굴 이모지 표정 screaming in fear",
	"😖": "괴로운 얼굴 이모지 표정 confounded face",
	"😣": "참고 있는 얼굴 이모지 표정 persevering face",
	"😞": "실망한 얼굴 이모지 표정 disappointed face",
	"😓": "식은땀 흘리며 낙담 이모지 표정 땀 downcast sweat",
	"😩": "지친 얼굴 이모지 표정 weary face",
	"😫": "진저리 나는 얼굴 이모지 표정 tired face",
	"🥱": "하품하는 얼굴 이모지 표정 yawning face",
	"😤": "씩씩대는 얼굴 이모지 표정 face with steam",
	"😡": "화난 붉은 얼굴 이모지 표정 화 pouting face",
	"😠": "화난 얼굴 이모지 표정 화 angry face",
	"🤬": "욕하는 얼굴 이모지 표정 화 cursing face",
	"😈": "뿔 달린 웃는 얼굴 이모지 표정 devil smiling horns",
	"👿": "뿔 달린 화난 얼굴 이모지 표정 angry devil",
	"💀": "해골 이모지 죽음 skull",
	"💩": "똥 이모지 poop",
	"🤡": "광대 이모지 표정 clown face",
	"👻": "유령 이모지 ghost",
	"👽": "외계인 이모지 alien",
	"🤖": "로봇 이모지 robot",
	"😺": "웃는 고양이 이모지 고양이 grinning cat",
	"😻": "하트 눈 고양이 이모지 고양이 heart eyes cat",
	"😹": "눈물 나게 웃는 고양이 이모지 고양이 cat tears of joy",
	"🙀": "놀란 고양이 이모지 고양이 weary cat",
	"😿": "우는 고양이 이모지 고양이 crying cat",
	"🙈": "눈 가린 원숭이 이모지 원숭이 see no evil monkey",
	"🙉": "귀 막은 원숭이 이모지 원숭이 hear no evil monkey",
	"🙊": "입 막은 원숭이 이모지 원숭이 speak no evil monkey",
	"👍": "엄지척 이모지 손 좋아요 thumbs up",
	"👎": "엄지 아래 이모지 손 싫어요 thumbs down",
	"👌": "오케이 손 이모지 손 ok hand",
	"✌": "브이 이모지 손 victory hand peace",
	"🤞": "행운을 비는 손 이모지 손 crossed fingers",
	"🤟": "사랑해 손 이모지 손 love you gesture",
	"🤘": "뿔 손 이모지 손 sign of the horns",
	"🤙": "전화해 손 이모지 손 call me hand",
	"👈": "왼쪽 가리키는 손 이모지 손 backhand index left",
	"👉": "오른쪽 가리키는 손 이모지 손 backhand index right",
	"👆": "위 가리키는 손 이모지 손 backhand index up",
	"👇": "아래 가리키는 손 이모지 손 backhand index down",
	"✋": "든 손 이모지 손 raised hand",
	"🤚": "손등 이모지 손 raised back of hand",
	"🖐": "손가락 편 손 이모지 손 hand with fingers splayed",
	"🖖": "벌칸 인사 이모지 손 vulcan salute",
	"👋": "흔드는 손 이모지 손 인사 waving hand",
	"🤏": "조금 이모지 손 pinching hand",
	"✊": "주먹 이모지 손 raised fist",
	"👊": "앞으로 내민 주먹 이모지 손 oncoming fist",
	"🤛": "왼쪽 주먹 이모지 손 left facing fist",
	"🤜": "오른쪽 주먹 이모지 손 right facing fist",
	"👏": "박수 이모지 손 clapping hands",
	"🙌": "두 손 들기 이모지 손 raising hands",
	"👐": "벌린 두 손 이모지 손 open hands",
	"🤲": "받치는 두 손 이모지 손 palms up together",
	"🤝": "악수 이모지 손 handshake",
	"🙏": "기도하는 손 이모지 손 감사 folded hands please thanks",
	"💅": "매니큐어 이모지 손 nail polish",
	"💪": "알통 이모지 근육 flexed biceps muscle",
	"👀": "두 눈 이모지 눈 eyes",
	"👁": "눈 이모지 눈 eye",
	"👂": "귀 이모지 ear",
	"👃": "코 이모지 nose",
	"👄": "입술 이모지 mouth lips",
	"👅": "혀 이모지 tongue",
	"🦷": "이 이모지 tooth",
	"🧠": "뇌 이모지 brain",
	"🦴": "뼈 이모지 bone",
	"👶": "아기 이모지 사람 baby",
	"🧒": "아이 이모지 사람 child",
	"👦": "남자아이 이모지 사람 boy",
	"👧": "여자아이 이모지 사람 girl",
	"🧑": "사람 이모지 사람 person adult",
	"👨": "남자 이모지 사람 man",
	"👩": "여자 이모지 사람 woman",
	"🧓": "노인 이모지 사람 older person",
	"👴": "할아버지 이모지 사람 old man",
	"👵": "할머니 이모지 사람 old woman",
	"🙋": "손 든 사람 이모지 사람 person raising hand",
	"🙇": "절하는 사람 이모지 사람 person bowing",
	"🤦": "이마 짚는 사람 이모지 사람 person facepalming",
	"🤷": "어깨 으쓱 이모지 사람 person shrugging",
	"💁": "안내하는 사람 이모지 사람 person tipping hand",
	"🙅": "안 된다는 사람 이모지 사람 person gesturing no",
	"🙆": "된다는 사람 이모지 사람 person gesturing ok",
	"🚶": "걷는 사람 이모지 사람 person walking",
	"🏃": "달리는 사람 이모지 사람 person running",
	"💃": "춤추는 여자 이모지 사람 woman dancing",
	"🕺": "춤추는 남자 이모지 사람 man dancing",
	"👮": "경찰관 이모지 사람 police officer",
	"👷": "건설 노동자 이모지 사람 construction worker",
	"💂": "근위병 이모지 사람 guard",
	"🕵": "탐정 이모지 사람 detective",
	"🎅": "산타클로스 이모지 사람 크리스마스 santa claus",
	"🦸": "슈퍼히어로 이모지 사람 superhero",
	"🧙": "마법사 이모지 사람 mage wizard",
	"🧚": "요정 이모지 사람 fairy",
	"👯": "토끼 귀 사람 이모지 사람 people with bunny ears",
	"👪": "가족 이모지 사람 family",
	"👫": "손잡은 남녀 이모지 사람 woman and man holding hands",
	"💏": "키스하는 사람들 이모지 사람 kiss",
	"💑": "사랑하는 사람들 이모지 사람 couple with heart",
	"👤": "실루엣 이모지 사람 bust in silhouette",
	"👥": "실루엣 둘 이모지 사람 busts in silhouette",
	"🗣": "말하는 얼굴 이모지 사람 speaking head",
	"🦶": "발 이모지 foot",
	"🦵": "다리 이모지 leg",
	"❤": "빨간 하트 이모지 하트 사랑 red heart",
	"🧡": "주황 하트 이모지 하트 사랑 orange heart",
	"💛": "노란 하트 이모지 하트 사랑 yellow heart",
	"💚": "초록 하트 이모지 하트 사랑 green heart",
	"💙": "파란 하트 이모지 하트 사랑 blue heart",
	"💜": "보라 하트 이모지 하트 사랑 purple heart",
	"🖤": "검은 하트 이모지 하트 사랑 black heart",
	"🤍": "흰 하트 이모지 하트 사랑 white heart",
	"🤎": "갈색 하트 이모지 하트 사랑 brown heart",
	"💔": "깨진 하트 이모지 하트 이별 broken heart",
	"❣": "느낌표 하트 이모지 하트 heart exclamation",
	"💕": "하트 두 개 이모지 하트 사랑 two hearts",
	"💞": "도는 하트 이모지 하트 사랑 revolving hearts",
	"💓": "뛰는 하트 이모지 하트 사랑 beating heart",
	"💗": "커지는 하트 이모지 하트 사랑 growing heart",
	"💖": "반짝이는 하트 이모지 하트 사랑 sparkling heart",
	"💘": "화살 꽂힌 하트 이모지 하트 사랑 heart with arrow cupid",
	"💝": "리본 달린 하트 이모지 하트 선물 heart with ribbon",
	"💟": "하트 장식 이모지 하트 heart decoration",
	"💌": "연애편지 이모지 하트 love letter",
	"💋": "입술 자국 이모지 뽀뽀 kiss mark",
	"💯": "백점 이모지 hundred points",
	"💢": "분노 표시 이모지 화 anger symbol",
	"💥": "충돌 이모지 collision boom",
	"💫": "어지러움 이모지 별 dizzy star",
	"💦": "땀방울 이모지 땀 sweat droplets",
	"💨": "쌩 이모지 dashing away",
	"🕳": "구멍 이모지 hole",
	"💣": "폭탄 이모지 bomb",
	"💬": "말풍선 이모지 speech balloon",
	"💭": "생각 풍선 이모지 thought balloon",
	"🗯": "분노 풍선 이모지 right anger bubble",
	"💤": "잠 이모지 zzz sleep",
	"🔥": "불 이모지 fire",
	"⭐": "별 이모지 별 star",
	"🌟": "반짝이는 별 이모지 별 glowing star",
	"✅": "초록 체크 이모지 체크 확인 check mark button",
	"❌": "엑스 표시 이모지 엑스 취소 cross mark",
	"❎": "엑스 상자 이모지 엑스 cross mark button",
	"➕": "더하기 이모지 plus",
	"➖": "빼기 이모지 minus",
	"➗": "나누기 이모지 divide",
	"❓": "물음표 이모지 question mark",
	"❔": "흰 물음표 이모지 white question mark",
	"❗": "느낌표 이모지 exclamation mark",
	"❕": "흰 느낌표 이모지 white exclamation mark",
	"🚫": "금지 이모지 prohibited no entry",
	"⛔": "진입 금지 이모지 no entry",
	"💡": "전구 이모지 아이디어 light bulb idea",
	"🔔": "종 이모지 알림 bell",
	"🔕": "종 금지 이모지 알림 bell with slash mute",
	"📌": "압정 이모지 pushpin",
	"📍": "위치 핀 이모지 위치 round pushpin location",
	"🔖": "책갈피 이모지 bookmark",
	"🏷": "꼬리표 이모지 label tag",
	"🔗": "고리 이모지 링크 link",
	"📎": "클립 이모지 paperclip",
	"🔒": "잠김 이모지 locked",
	"🔓": "열림 이모지 unlocked",
	"🔑": "열쇠 이모지 key",
	"🔍": "돋보기 이모지 검색 magnifying glass search",
	"🔎": "오른쪽 돋보기 이모지 검색 magnifying glass right",
	"🔄": "순환 화살표 이모지 새로고침 counterclockwise arrows refresh",
	"🔁": "반복 이모지 repeat",
	"🔀": "섞기 이모지 shuffle",
	"🆗": "오케이 이모지 ok button",
	"🆕": "새로움 이모지 new button",
	"🆙": "업 이모지 up button",
	"🔝": "맨 위 이모지 top arrow",
	"🎉": "크래커 이모지 축하 party popper",
	"🎊": "색종이 공 이모지 축하 confetti ball",
	"🎈": "풍선 이모지 축하 balloon",
	"🎁": "선물 이모지 선물 gift",
	"🏆": "트로피 이모지 상 trophy",
	"🥇": "금메달 이모지 상 gold medal",
	"🥈": "은메달 이모지 상 silver medal",
	"🥉": "동메달 이모지 상 bronze medal",
	"🎯": "과녁 이모지 목표 direct hit target",
	"🚀": "로켓 이모지 rocket",
	"💎": "보석 이모지 gem stone diamond",
	"👑": "왕관 이모지 crown",
	"🐶": "강아지 얼굴 이모지 동물 개 dog face",
	"🐕": "개 이모지 동물 dog",
	"🐱": "고양이 얼굴 이모지 동물 고양이 cat face",
	"🐈": "고양이 이모지 동물 cat",
	"🐭": "쥐 얼굴 이모지 동물 mouse face",
	"🐹": "햄스터 이모지 동물 hamster",
	"🐰": "토끼 얼굴 이모지 동물 rabbit face",
	"🦊": "여우 이모지 동물 fox",
	"🐻": "곰 이모지 동물 bear",
	"🐼": "판다 이모지 동물 panda",
	"🐨": "코알라 이모지 동물 koala",
	"🐯": "호랑이 얼굴 이모지 동물 tiger face",
	"🦁": "사자 이모지 동물 lion",
	"🐮": "소 얼굴 이모지 동물 cow face",
	"🐷": "돼지 얼굴 이모지 동물 pig face",
	"🐽": "돼지 코 이모지 동물 pig nose",
	"🐸": "개구리 이모지 동물 frog",
	"🐵": "원숭이 얼굴 이모지 동물 monkey face",
	"🐒": "원숭이 이모지 동물 monkey",
	"🐔": "닭 이모지 동물 chicken",
	"🐧": "펭귄 이모지 동물 penguin",
	"🐦": "새 이모지 동물 bird",
	"🐤": "병아리 이모지 동물 baby chick",
	"🦆": "오리 이모지 동물 duck",
	"🦅": "독수리 이모지 동물 eagle",
	"🦉": "올빼미 이모지 동물 owl",
	"🦇": "박쥐 이모지 동물 bat",
	"🐺": "늑대 이모지 동물 wolf",
	"🐗": "멧돼지 이모지 동물 boar",
	"🐴": "말 얼굴 이모지 동물 horse face",
	"🦄": "유니콘 이모지 동물 unicorn",
	"🐝": "꿀벌 이모지 동물 honeybee",
	"🐛": "애벌레 이모지 동물 bug caterpillar",
	"🦋": "나비 이모지 동물 butterfly",
	"🐌": "달팽이 이모지 동물 snail",
	"🐞": "무당벌레 이모지 동물 lady beetle",
	"🐜": "개미 이모지 동물 ant",
	"🕷": "거미 이모지 동물 spider",
	"🕸": "거미줄 이모지 spider web",
	"🦂": "전갈 이모지 동물 scorpion",
	"🐢": "거북 이모지 동물 turtle",
	"🐍": "뱀 이모지 동물 snake",
	"🦎": "도마뱀 이모지 동물 lizard",
	"🐙": "문어 이모지 동물 octopus",
	"🦑": "오징어 이모지 동물 squid",
	"🦐": "새우 이모지 동물 shrimp",
	"🦀": "게 이모지 동물 crab",
	"🐡": "복어 이모지 동물 blowfish",
	"🐠": "열대어 이모지 동물 tropical fish",
	"🐟": "물고기 이모지 동물 fish",
	"🐬": "돌고래 이모지 동물 dolphin",
	"🐳": "고래 이모지 동물 whale",
	"🦈": "상어 이모지 동물 shark",
	"🐊": "악어 이모지 동물 crocodile",
	"🐘": "코끼리 이모지 동물 elephant",
	"🦏": "코뿔소 이모지 동물 rhinoceros",
	"🐪": "낙타 이모지 동물 camel",
	"🦒": "기린 이모지 동물 giraffe",
	"🐇": "토끼 이모지 동물 rabbit",
	"🐿": "다람쥐 이모지 동물 chipmunk",
	"🦔": "고슴도치 이모지 동물 hedgehog",
	"🐾": "발자국 이모지 동물 paw prints",
	"🌸": "벚꽃 이모지 꽃 cherry blossom",
	"💮": "흰 꽃 이모지 꽃 white flower",
	"🌹": "장미 이모지 꽃 rose",
	"🥀": "시든 꽃 이모지 꽃 wilted flower",
	"🌺": "무궁화 이모지 꽃 hibiscus",
	"🌻": "해바라기 이모지 꽃 sunflower",
	"🌼": "블로섬 이모지 꽃 blossom",
	"🌷": "튤립 이모지 꽃 tulip",
	"🌱": "새싹 이모지 식물 seedling",
	"🌲": "침엽수 이모지 나무 evergreen tree",
	"🌳": "활엽수 이모지 나무 deciduous tree",
	"🌴": "야자수 이모지 나무 palm tree",
	"🌵": "선인장 이모지 식물 cactus",
	"🍀": "네잎클로버 이모지 행운 four leaf clover",
	"🍁": "단풍잎 이모지 잎 maple leaf",
	"🍂": "낙엽 이모지 잎 fallen leaf",
	"🍃": "바람에 날리는 잎 이모지 잎 leaf fluttering",
	"🌾": "벼 이모지 식물 sheaf of rice",
	"🌍": "지구 유럽아프리카 이모지 지구 globe europe africa",
	"🌏": "지구 아시아 이모지 지구 globe asia australia",
	"🌎": "지구 아메리카 이모지 지구 globe americas",
	"🌕": "보름달 이모지 달 full moon",
	"🌑": "삭 이모지 달 new moon",
	"🌙": "초승달 이모지 달 crescent moon",
	"🌛": "웃는 상현달 이모지 달 first quarter moon face",
	"🌞": "웃는 해 이모지 날씨 sun with face",
	"⛅": "구름 낀 해 이모지 날씨 sun behind cloud",
	"🌧": "비 오는 구름 이모지 날씨 비 cloud with rain",
	"⛈": "번개 치는 구름 이모지 날씨 cloud with lightning rain",
	"🌩": "번개 이모지 날씨 cloud with lightning",
	"⛄": "눈사람 없는 눈 이모지 날씨 눈 snowman without snow",
	"🌈": "무지개 이모지 날씨 rainbow",
	"🌊": "파도 이모지 물 water wave",
	"💧": "물방울 이모지 물 droplet",
	"🌋": "화산 이모지 자연 volcano",
	"⛰": "산 이모지 자연 mountain",
	"🏔": "눈 덮인 산 이모지 자연 snow capped mountain",
	"🌅": "일출 이모지 자연 sunrise",
	"🌄": "산 위 일출 이모지 자연 sunrise over mountains",
	"🌇": "일몰 이모지 자연 sunset",
	"🌌": "은하수 이모지 자연 milky way",
	"🍎": "빨간 사과 이모지 음식 과일 red apple",
	"🍏": "초록 사과 이모지 음식 과일 green apple",
	"🍐": "배 이모지 음식 과일 pear",
	"🍊": "귤 이모지 음식 과일 tangerine orange",
	"🍋": "레몬 이모지 음식 과일 lemon",
	"🍌": "바나나 이모지 음식 과일 banana",
	"🍉": "수박 이모지 음식 과일 watermelon",
	"🍇": "포도 이모지 음식 과일 grapes",
	"🍓": "딸기 이모지 음식 과일 strawberry",
	"🍑": "복숭아 이모지 음식 과일 peach",
	"🍒": "체리 이모지 음식 과일 cherries",
	"🥝": "키위 이모지 음식 과일 kiwi",
	"🍍": "파인애플 이모지 음식 과일 pineapple",
	"🥥": "코코넛 이모지 음식 과일 coconut",
	"🥑": "아보카도 이모지 음식 avocado",
	"🍅": "토마토 이모지 음식 tomato",
	"🍆": "가지 이모지 음식 eggplant",
	"🥕": "당근 이모지 음식 carrot",
	"🌽": "옥수수 이모지 음식 corn",
	"🌶": "고추 이모지 음식 hot pepper",
	"🥔": "감자 이모지 음식 potato",
	"🍠": "고구마 이모지 음식 roasted sweet potato",
	"🧄": "마늘 이모지 음식 garlic",
	"🧅": "양파 이모지 음식 onion",
	"🥦": "브로콜리 이모지 음식 broccoli",
	"🍄": "버섯 이모지 음식 mushroom",
	"🥜": "땅콩 이모지 음식 peanuts",
	"🌰": "밤 이모지 음식 chestnut",
	"🍞": "식빵 이모지 음식 bread",
	"🥐": "크루아상 이모지 음식 croissant",
	"🥖": "바게트 이모지 음식 baguette",
	"🥨": "프레첼 이모지 음식 pretzel",
	"🧀": "치즈 이모지 음식 cheese",
	"🥚": "달걀 이모지 음식 egg",
	"🍳": "달걀 프라이 이모지 음식 cooking fried egg",
	"🥞": "팬케이크 이모지 음식 pancakes",
	"🥓": "베이컨 이모지 음식 bacon",
	"🍔": "햄버거 이모지 음식 hamburger",
	"🍟": "감자튀김 이모지 음식 french fries",
	"🍕": "피자 이모지 음식 pizza",
	"🌭": "핫도그 이모지 음식 hot dog",
	"🥪": "샌드위치 이모지 음식 sandwich",
	"🌮": "타코 이모지 음식 taco",
	"🌯": "부리토 이모지 음식 burrito",
	"🥗": "샐러드 이모지 음식 green salad",
	"🍝": "스파게티 이모지 음식 spaghetti",
	"🍜": "라면 이모지 음식 steaming bowl ramen",
	"🍲": "전골 이모지 음식 pot of food",
	"🍛": "카레 이모지 음식 curry rice",
	"🍚": "밥 이모지 음식 cooked rice",
	"🍙": "주먹밥 이모지 음식 rice ball",
	"🍘": "전병 이모지 음식 rice cracker",
	"🍢": "어묵꼬치 이모지 음식 oden",
	"🍡": "경단 이모지 음식 dango",
	"🍣": "초밥 이모지 음식 sushi",
	"🍤": "새우튀김 이모지 음식 fried shrimp",
	"🍥": "어묵 이모지 음식 fish cake",
	"🥟": "만두 이모지 음식 dumpling",
	"🍦": "소프트 아이스크림 이모지 음식 soft ice cream",
	"🍨": "아이스크림 이모지 음식 ice cream",
	"🍧": "빙수 이모지 음식 shaved ice",
	"🍩": "도넛 이모지 음식 doughnut",
	"🍪": "쿠키 이모지 음식 cookie",
	"🎂": "생일 케이크 이모지 음식 birthday cake",
	"🍰": "조각 케이크 이모지 음식 shortcake",
	"🧁": "컵케이크 이모지 음식 cupcake",
	"🍫": "초콜릿 이모지 음식 chocolate bar",
	"🍬": "사탕 이모지 음식 candy",
	"🍭": "막대사탕 이모지 음식 lollipop",
	"🍮": "푸딩 이모지 음식 custard pudding",
	"🍯": "꿀 이모지 음식 honey pot",
	"🥛": "우유 이모지 음료 glass of milk",
	"🍵": "녹차 이모지 음료 teacup",
	"🍶": "사케 이모지 음료 sake",
	"🍺": "맥주 이모지 음료 beer mug",
	"🍻": "맥주 건배 이모지 음료 clinking beer mugs",
	"🥂": "샴페인 건배 이모지 음료 clinking glasses",
	"🍷": "와인 이모지 음료 wine glass",
	"🥃": "위스키 이모지 음료 tumbler glass",
	"🍸": "칵테일 이모지 음료 cocktail glass",
	"🍹": "트로피컬 음료 이모지 음료 tropical drink",
	"🍾": "샴페인 이모지 음료 bottle with popping cork",
	"🧊": "얼음 이모지 음료 ice",
	"🥄": "숟가락 이모지 식기 spoon",
	"🍴": "포크와 나이프 이모지 식기 fork and knife",
	"🍽": "접시와 식기 이모지 식기 plate with cutlery",
	"🥢": "젓가락 이모지 식기 chopsticks",
	"💻": "노트북 이모지 컴퓨터 laptop",
	"🖥": "데스크톱 이모지 컴퓨터 desktop computer",
	"🖨": "프린터 이모지 printer",
	"⌨": "키보드 이모지 keyboard",
	"🖱": "마우스 이모지 computer mouse",
	"💾": "플로피 디스크 이모지 저장 floppy disk save",
	"💿": "시디 이모지 optical disk cd",
	"📀": "디비디 이모지 dvd",
	"💽": "미니 디스크 이모지 computer disk",
	"📱": "휴대전화 이모지 mobile phone",
	"📲": "전화 오는 휴대전화 이모지 mobile phone with arrow",
	"📞": "수화기 이모지 telephone receiver",
	"📟": "호출기 이모지 pager",
	"📠": "팩스 이모지 fax machine",
	"🔋": "배터리 이모지 battery",
	"🔌": "플러그 이모지 electric plug",
	"🔦": "손전등 이모지 flashlight",
	"📷": "사진기 이모지 camera",
	"📸": "플래시 사진기 이모지 camera with flash",
	"📹": "비디오 카메라 이모지 video camera",
	"🎥": "영화 카메라 이모지 movie camera",
	"📺": "텔레비전 이모지 television",
	"📻": "라디오 이모지 radio",
	"🎙": "마이크 이모지 studio microphone",
	"🎤": "노래 마이크 이모지 microphone",
	"🎧": "헤드폰 이모지 headphone",
	"🎵": "음표 이모지 음악 musical note",
	"🎶": "여러 음표 이모지 음악 musical notes",
	"🎼": "악보 이모지 음악 musical score",
	"🎹": "건반 이모지 음악 musical keyboard piano",
	"🎸": "기타 이모지 음악 guitar",
	"🥁": "드럼 이모지 음악 drum",
	"🎺": "트럼펫 이모지 음악 trumpet",
	"🎻": "바이올린 이모지 음악 violin",
	"📖": "펼친 책 이모지 책 open book",
	"📚": "책 여러 권 이모지 책 books",
	"📕": "닫힌 책 이모지 책 closed book",
	"📓": "공책 이모지 책 notebook",
	"📔": "장식 공책 이모지 책 notebook with cover",
	"📒": "장부 이모지 책 ledger",
	"📃": "말린 문서 이모지 문서 page with curl",
	"📄": "문서 이모지 문서 page facing up",
	"📑": "책갈피 탭 이모지 문서 bookmark tabs",
	"📊": "막대 그래프 이모지 그래프 bar chart",
	"📈": "오름 그래프 이모지 그래프 chart increasing",
	"📉": "내림 그래프 이모지 그래프 chart decreasing",
	"📋": "클립보드 이모지 clipboard",
	"📁": "폴더 이모지 file folder",
	"📂": "열린 폴더 이모지 open file folder",
	"🗂": "분류 폴더 이모지 card index dividers",
	"🗃": "서류함 이모지 card file box",
	"🗄": "캐비닛 이모지 file cabinet",
	"🗑": "휴지통 이모지 삭제 wastebasket trash",
	"🖊": "볼펜 이모지 pen",
	"🖋": "만년필 이모지 fountain pen",
	"🖌": "붓 이모지 paintbrush",
	"🖍": "크레용 이모지 crayon",
	"📝": "메모 이모지 memo writing",
	"📐": "삼각자 이모지 triangular ruler",
	"📏": "직선자 이모지 straight ruler",
	"🔨": "망치 이모지 도구 hammer",
	"🔧": "렌치 이모지 도구 wrench",
	"🔩": "나사 이모지 도구 nut and bolt",
	"🧰": "공구함 이모지 도구 toolbox",
	"🪛": "드라이버 이모지 도구 screwdriver",
	"⛏": "곡괭이 이모지 도구 pick",
	"🧲": "자석 이모지 magnet",
	"🧪": "시험관 이모지 과학 test tube",
	"🔬": "현미경 이모지 과학 microscope",
	"🔭": "망원경 이모지 과학 telescope",
	"💉": "주사기 이모지 의료 syringe",
	"💊": "알약 이모지 의료 pill",
	"🩹": "반창고 이모지 의료 adhesive bandage",
	"🛏": "침대 이모지 bed",
	"🚪": "문 이모지 door",
	"🪟": "창문 이모지 window",
	"🧹": "빗자루 이모지 broom",
	"🧺": "바구니 이모지 basket",
	"💰": "돈주머니 이모지 돈 money bag",
	"💵": "달러 지폐 이모지 돈 dollar banknote",
	"💳": "신용카드 이모지 돈 credit card",
	"🧾": "영수증 이모지 돈 receipt",
	"📦": "상자 이모지 package box",
	"📮": "우체통 이모지 postbox",
	"📧": "이메일 이모지 메일 e-mail",
	"📨": "받은 편지 이모지 메일 incoming envelope",
	"📩": "보낸 편지 이모지 메일 envelope with arrow",
	"🔐": "잠긴 자물쇠와 열쇠 이모지 보안 locked with key",
	"🛡": "방패 이모지 보안 shield",
	"⚽": "축구공 이모지 운동 soccer ball",
	"🏀": "농구공 이모지 운동 basketball",
	"⚾": "야구공 이모지 운동 baseball",
	"🎾": "테니스공 이모지 운동 tennis",
	"🏐": "배구공 이모지 운동 volleyball",
	"🏈": "미식축구공 이모지 운동 american football",
	"🎱": "당구공 이모지 운동 pool 8 ball",
	"🏓": "탁구 이모지 운동 ping pong",
	"🏸": "배드민턴 이모지 운동 badminton",
	"🥊": "권투 글러브 이모지 운동 boxing glove",
	"🎮": "게임 패드 이모지 게임 video game",
	"🕹": "조이스틱 이모지 게임 joystick",
	"🎲": "주사위 이모지 게임 game die",
	"🧩": "퍼즐 이모지 게임 puzzle piece",
	"♟": "체스 폰 이모지 게임 chess pawn",
	"🎬": "슬레이트 이모지 영화 clapper board",
	"🎭": "가면 이모지 예술 performing arts",
	"🎨": "팔레트 이모지 예술 artist palette",
	"🚗": "자동차 이모지 교통 car",
	"🚕": "택시 이모지 교통 taxi",
	"🚌": "버스 이모지 교통 bus",
	"🚑": "구급차 이모지 교통 ambulance",
	"🚒": "소방차 이모지 교통 fire engine",
	"🚲": "자전거 이모지 교통 bicycle",
	"🛴": "킥보드 이모지 교통 kick scooter",
	"🏍": "오토바이 이모지 교통 motorcycle",
	"🚂": "기관차 이모지 교통 locomotive",
	"🚆": "기차 이모지 교통 train",
	"🚇": "지하철 이모지 교통 metro",
	"🚁": "헬리콥터 이모지 교통 helicopter",
	"🚢": "배 이모지 교통 ship",
	"⛵": "돛단배 이모지 교통 sailboat",
	"🚦": "신호등 이모지 교통 traffic light",
	"🏠": "집 이모지 장소 house",
	"🏢": "건물 이모지 장소 office building",
	"🏫": "학교 이모지 장소 school",
	"🏥": "병원 이모지 장소 hospital",
	"🏦": "은행 이모지 장소 bank",
	"🏪": "편의점 이모지 장소 convenience store",
	"⛺": "텐트 이모지 장소 tent",
	"🗺": "지도 이모지 장소 world map",
	"🧭": "나침반 이모지 장소 compass",
	"🕐": "한 시 이모지 시계 one o clock",
	"📅": "달력 이모지 날짜 calendar",
	"📆": "찢는 달력 이모지 날짜 tear off calendar",
}
